[package]
name = "tictactoe-manager"
version = "0.0.0"
authors = ["K"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }
stellar-xdr = { workspace = true, features = ["next", "std"], optional = true }

[dev_dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }