name: NodeJS

on:
  push:
    branches: [main]
  pull_request:

jobs:

  complete:
    if: always()
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: stellar/actions/rust-cache@main
    - run: rustup update
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install --target-dir ~/.cargo/target --locked --version 0.7.1 soroban-cli
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        cache: 'npm'
    - run: npm ci
    - run: |
        mkdir -p .soroban
        echo 'a9ab643486dc0dbcdc1485e6589e8bb3bcbbd8e69ad66c703556b4d6645a6dc8' > .soroban/token_id
        echo 'GDT2NORMZF6S2T4PT4OBJJ43OPD3GPRNTJG3WVVFB356TUHWZQMU6C3U' > .soroban/token_admin_address
        echo 'SAKCFFFNCE7XAWYMYVRZQYKUK6KMUCDIINLWISJYTMYJLNR2QLCDLFVT' > .soroban/token_admin_secret
        echo 'ac15f8574641c04e3edb12384ac6a95fac4a35e1da7d4a4b192ed7db9628d314' > .soroban/game_id
        echo 'b850a708714cd91a980f735f9c74cdfb359a5b68310e827c658af7f9ed01e0f6' > .soroban/deployer_id
    - run: npm run-script build
